concerto_cms_news:
    pattern:  /news
    defaults: { _controller: ConcertoCmsNewsBundle:News:index }

# API
concerto_cms_news_rest:
    pattern:  /rest/news
    defaults: { _controller: ConcertoCmsNewsBundle:News:get }
    methods:  [GET]

concerto_cms_news_rest_new:
    pattern: /rest/news/{path}
    defaults: { _controller: ConcertoCmsNewsBundle:News:post }
    requirements:
        path:   .*
    methods:  [POST]
    options:
        expose: true

concerto_cms_news_rest_save:
    pattern: /rest/news/{path}
    defaults: { _controller: ConcertoCmsNewsBundle:News:put }
    methods:  [PUT]
    requirements:
        path:   .*
    options:
        expose: true
