parameters:
#    concerto_cms_news.example.class: ConcertoCms\NewsBundle\Example

services:
     concerto_cms_news.news:
         class: ConcertoCms\NewsBundle\Service\News
         arguments: [@doctrine_phpcr.odm.default_document_manager]
#     concerto_cms_news.pagemanager.newsitem:
#         class: ConcertoCms\NewsBundle\PageManager\NewsItem
#         tags:
#            - { name: concerto.pagemanager}
     concerto_cms_news.pagemanager:
         class: ConcertoCms\NewsBundle\Service\PageManager
         tags:
            - { name: concerto.pagemanager}
     concerto_cms_news.extension.mainmenu:
         class: ConcertoCms\NewsBundle\Extension\MainMenuListener
         tags:
            - name: kernel.event_listener
              event: concerto.menu.main.build
              method: onBuild
