parameters:
#    concerto_cms_news.example.class: ConcertoCms\NewsBundle\Example

services:
#    concerto_cms_news.example:
#        class: %concerto_cms_news.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
